# frozen_string_literal: true
# Gemfile para AMAR.
source "https://rubygems.org"

# Controla los puertos GPIO de la Raspberry Pi.
# TODO arreglar cuando el dueño de la gema la actualice.
gem "rpi_gpio", :git => 'https://github.com/nicolassatragno/rpi_gpio.git'
