# frozen_string_literal: true
# Gemfile para AMAR.
source "https://rubygems.org"

# Manejan la API.
gem "sinatra"
gem "thin"

# Controla los puertos GPIO de la Raspberry Pi.
gem "rpi_gpio"
gem "rpi-hd44780"

# Maneja la planificación.
gem 'rufus-scheduler'

# Testing.
gem "rspec"
